global:
  sendAnonymousUsage: false
log:
  level: INFO
api:
  dashboard: true

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
