[project]
name = "common-schemas"
version = "0.1.0"
description = "Common Pydantic models for OpenQuiz BFF"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["pydantic>=2.7"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
